# Azure only builds master

trigger:
  branches:
    include:
      - 'refs/tags/*'
      - master
    exclude:
      - next_*
pr:
  - master

variables:
  package_name: MCEq
  many_linux_base: quay.io/pypa/manylinux1_
  dev_requirements_file: .ci/requirements-build.txt
  test_requirements_file: .ci/requirements-test.txt

jobs:
  
- job: LinuxSDist
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    python.architecture: 'none'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    - script: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
      displayName: Install sdist deps
    - script: python setup.py sdist
      displayName: Prepare sdist
    - template: .ci/azure-publish-dist.yml

- job: ManyLinux
  strategy:
    matrix:
      64Bit2010:
        arch: x86_64
        plat: manylinux2010_x86_64
        image: quay.io/pypa/manylinux2010_x86_64
        python.architecture: x64
#       64Bit:
#         arch: x86_64
#         plat: manylinux1_x86_64
#         image: $(many_linux_base)x86_64
#         python.architecture: x64
#       32Bit:
#         arch: i686
#         plat: manylinux1_i686
#         image: $(many_linux_base)i686
#         python.architecture: x86
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: .ci/azure-manylinux-wheels.yml
    - template: .ci/azure-publish-dist.yml

- job: ManyLinux_AArch64
  strategy:
    matrix:
      64Bit2014:
        arch: aarch64
        plat: manylinux2014_aarch64
        image: quay.io/pypa/manylinux2014_aarch64
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: docker run --rm --privileged hypriot/qemu-register
      displayName: 'Registering qemu'
    - template: .ci/azure-manylinux-wheels.yml
    - template: .ci/azure-publish-dist.yml

- job: macOS
  variables:
    python.architecture: 'x64'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
  pool:
    vmImage: 'macOS-latest'
  steps:
    - template: .ci/azure-setup.yml
    - template: .ci/azure-steps.yml
    - template: .ci/azure-tests.yml
    - template: .ci/azure-publish-dist.yml

- job: Windows
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        python.architecture: 'x64'
      Python36:
        python.version: '3.6'
        python.architecture: 'x64'
      Python37:
        python.version: '3.7'
        python.architecture: 'x64'
      Python38:
        python.version: '3.8'
        python.architecture: 'x64'
      Python39:
        python.version: '3.9'
        python.architecture: 'x64'
#       Python27_32:
#         python.version: '2.7'
#         python.architecture: 'x86'
#       Python36_32:
#         python.version: '3.6'
#         python.architecture: 'x86'
#       Python37_32:
#         python.version: '3.7'
#         python.architecture: 'x86'
#       Python38_32:
#         python.version: '3.8'
#         python.architecture: 'x86'
#       Python39_32:
#         python.version: '3.9'
#         python.architecture: 'x86'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - template: .ci/azure-setup.yml
    - template: .ci/azure-steps.yml
    - template: .ci/azure-tests.yml
    - template: .ci/azure-publish-dist.yml
